### ISSUE TITLE
making the ./gr-scan

### ISSUE THREAD

**Issue by albedo039** [RileyHL/gr-scan#1]
hello Riley..
i d'like to generate the ./gr-scan , but it won't make..
have you got the install howto ?

**Comment by RileyHL** [comment]
It should compile just by running make. What errors are you getting?

**Comment by albedo039** [comment]
so i find and put a "gr_top_block.h in usr/include because i adn't any one an when i run "make", it return me that : (it's in french...sorry...) 

g++ -DVERSION="\"gr-scan 2012082301\"" -std=c++11 -Wall -I/usr/include/gnuradio -I/usr/include/osmosdr -lgnuradio-core -lgnuradio-osmosdr -lboost_system -O2 -s -Wno-unused-function -o gr-scan main.cpp
In file included from /usr/include/gr_top_block.h:26:0,
                 from topblock.hpp:23,
                 from main.cpp:23:
/usr/include/gr_core_api.h:25:10: fatal error
compilation terminated.
Makefile:23 : la recette pour la cible « gr-scan » a échouée
make: *** [gr-scan] Erreur 1

**Comment by RileyHL** [comment]
From what I can tell, you need to make sure that gnuradio is installed properly. What system are you using and how did you install gnuradio?

**Comment by albedo039** [comment]
i use kali rolling for amd 64
i'd install gnuradio by "apt-get install gnuradio".. i even done "apt-get install gnuradio-dev" for develloppement...when i run gnuradio-companion it's ok but some key blocks  are not presents:

Block key "usrp_simple_source_x" not found
Block key "gr_freq_xlating_fir_filter_xxx" not found
Block key "blks2_wfm_rcv" not found
Block key "blks2_rational_resampler_xxx" not found
Block key "gr_multiply_const_vxx" not found
...bad !  :(

**Comment by RileyHL** [comment]
For the USRP source, you'll need gnuradio-osmosdr. Hopefully that is one issue down. As for the others, I don't have those blocks either, but they aren't used in gr-scan. Check /usr/include/gnuradio and make sure the header files included in the hpp files are present.

**Comment by albedo039** [comment]
all troubles are resolved for me in a ubuntu 16.04.lts , gnuradioand gqrx installed with rtlsdr tools...
it's ok....scan works good..
eaven gqrx,
amd64 / gr-scan2016014.zip 
make & test ok right now...

thanks for your attention....best..

**Comment by RileyHL** [comment]
Glad you got it figured out.
